---
# tasks file for splunk_all

- include: detect_splunk.yml
  tags:
    - always
    - detect_splunk

- include: user_config.yml
  tags:
    - user_config

- include: fips_mode.yml
  when: splunk_all_fips_mode | bool
  tags:
    - always
    - fips_mode

- include: general_p4sk.yml
  tags:
    - general_p4sk

- include: admin_login.yml
  tags:
    - always
    - admin_login
