---
# tasks file for splunk_all

- include: detect_splunk.yml
  tags:
    - always
    - detect_splunk

- include: user_config.yml
  tags:
    - user_config

- include: admin_login.yml
  tags:
    - always
    - admin_login
