---
language: python
os: linux
python:
  - "3.7"
services:
  - docker
install:
  - pip3 install -U molecule docker yamllint ansible-lint flake8 pluggy testinfra pytest takeltest
script:
  - molecule --version
  - ansible --version
  - ansible-lint ./
  - yamllint ./
  - cd roles/splunk_all && molecule test
