---
language: python
python:
  - "3.6"
services:
  - docker
install:
  - pip install molecule docker
  - pip install ansible-lint
  - pip install flake8
script:
  - molecule --version
  - ansible --version
  - cd roles/splunk_all && molecule test
