---
language: python
python:
  - "3.6"
services:
  - docker
install:
  - pip3 install molecule docker
  - pip3 install yamllint
  - pip3 install ansible-lint
  - pip3 install flake8
  - pip3 install takeltest
script:
  - molecule --version
  - ansible --version
  - cd roles/splunk_all && molecule test
