---
# Library Task... Include this to check / deploy a configuration app.

# How to use:
# - include: library/tasks/splunk_deploy_config_app.yml
#     task_bread_crumb=<name of the task that called this one eg: detect_splunk>
#     deploy_config_app_name=<name of app eg: default_ouputs,default_inputs etc...>
#     deploy_config_app_destpath=<path variable eg: "{{ splunk_all_splunk_appspath }}">
#     deploy_config_app_filename=<name of the splunk .conf file eg: indexes,server etc...>

- name: "{{ task_bread_crumb }} - splunk_deploy_config_app - CHECK / CREATE file path for {{ deploy_config_app_name }}"
  file:
    path: "{{ deploy_config_app_destpath }}/{{ splunk_all_default_prefix }}-{{ deploy_config_app_name }}/{{ item }}"
    recurse: no
    state: directory
    owner: "{{ splunk_all_splunk_user }}"
    group: "{{ splunk_all_splunk_group }}"
    mode: "{{ splunk_all_dir_mode }}"
  loop:
    - default
    - metadata

- name: "{{ task_bread_crumb }} - splunk_deploy_config_app - CHECK / DEPLOY default app.conf & default.meta file"
  copy:
    src: library/templates/common_files/{{ item.src }}
    dest: "{{ deploy_config_app_destpath }}/{{ splunk_all_default_prefix }}-{{ deploy_config_app_name }}/{{ item.dir }}/{{ item.src }}"
    owner: "{{ splunk_all_splunk_user }}"
    group: "{{ splunk_all_splunk_group }}"
    mode: "{{ splunk_all_file_mode }}"
  loop:
    - src: app.conf
      dir: default
    - src: default.meta
      dir: metadata

- name: "{{ task_bread_crumb }} - splunk_deploy_config_app - CHECK / DEPLOY {{ deploy_config_app_name }} {{ deploy_config_app_filename }} template"
  template:
    src: library/templates/{{ deploy_config_app_name }}/{{ deploy_config_app_filename }}
    dest: "{{ deploy_config_app_destpath }}/{{ splunk_all_default_prefix }}-{{ deploy_config_app_name }}/default/{{ deploy_config_app_filename }}"
    owner: "{{ splunk_all_splunk_user }}"
    group: "{{ splunk_all_splunk_group }}"
    mode: "{{ splunk_all_file_mode }}"
