# Library Task... Include this to detect if Splunk is running.
# Creates the detected_status variable that is a useful condition check for tasks dependent on splunk responses.
# How to use:
# - include: library/tasks/splunk_cli_detect_status.yml

- name: library_tasks - splunk_cli_detect_status - SPLUNK CLI command and register current_status
  command: "{{ splunk_all_cli_command }} status"
  register: current_status
  ignore_errors: yes
  failed_when: current_status.rc != 0

- name: library_tasks - splunk_cli_detect_status - SET a fact from current_status.stdout
  set_fact:
    detected_status: "{{ current_status.rc }}"
  when: current_status.rc == 0
