---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint ../splunk_all
  ansible-lint ../splunk_all
  flake8 ../splunk_all --exit-zero
platforms:
  - name: centos
    image: centos:7
  - name: ubuntu
    image: ubuntu:16.04
provisioner:
  name: ansible
verifier:
  name: testinfra
