---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  cd .. && yamllint splunk_all
  ansible-lint ./splunk_all
  flake8 ./splunk_all
platforms:
  - name: instance
    image: centos:7
provisioner:
  name: ansible
verifier:
  name: ansible
